---
title: "Лабораторная работа №2"
author: "Отчет Цуканова Леонтия Б20-902"
date: "Варинант №54"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r include=FALSE}
library(openxlsx)
library(ggplot2)
library(randomForest)
library(ggcorrplot)
library(GGally)
library(dplyr)

data <- read.xlsx(xlsxFile = "Вар_54_Полные_данные.xlsx")
```

``` {r include = FALSE}
# изменим названия для корректной работы с данными (иначе будет возникать ошибка)
x <- names(data)
del_comma <- function(x){
  x <- gsub(',','',x)
}
y <- sapply(x, del_comma)
colnames(data) <- y
colnames(data)[3] <-"Среднегодовой.доход.тыс"
colnames(data)[7] <-"Доля.от.дохода.семьи.которая.тратится.на.продовольствие"
colnames(data)[9] <- "Издержки.сообщества.на.окружающую.среду.млн."
colnames(data)[10] <- "Охват.беспроводной.связи.в.сообществе"
```

``` {r include=FALSE}
data$Ощущаемое.счастье <- as.factor(data$Ощущаемое.счастье)
no_data <- subset(data, data$Ощущаемое.счастье == 'Неизвестно') # данный дата фрейм необходимо было заполнить в конце для того, чтобы преподаватель мог оценить точность модели 
learn_data <- subset(data, data$Ощущаемое.счастье != 'Неизвестно')
```

``` {r, include = FALSE, warning = FALSE}
# разбиваем выборку на обучаующую и тестовую 
set.seed(111)
index = sample(1:nrow(learn_data), nrow(learn_data)*0.75) 
train_data <- learn_data[index, ]
test_data <- learn_data[-index, ]
```


``` {r, include = FALSE, warning = FALSE}
# Чтобы посмотреть корреляцию качественных признаков необходимо их проранжирвоать и построить корреляционную матрицу 
the_cantril_scale <- c('Hopeless', 'Depressed', 'Suffering', 'Strugglng', 'Coping', 'Just ok', 'Doing well', 'Blooming', 'Thriving', 'Prospering')
rang <- c(1:10)
data_corr <- train_data
data_corr$Ощущаемое.счастье <- as.character(data_corr$Ощущаемое.счастье)
data_corr$Ощущаемое.счастье_Шкала <- data_corr$Ощущаемое.счастье
for (i in 1:10) {
  data_corr[data_corr$Ощущаемое.счастье == the_cantril_scale[i], 27] <- as.numeric(rang[i])
}
data_corr <- data_corr[order(data_corr$Ощущаемое.счастье_Шкала),]
```

``` {r, echo = FALSE}
new_name <- c('V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27')
colnames(data_corr) <- new_name
data_corr$V27 <- as.numeric(data_corr$V27)
cor_mat <- cor(data_corr[,c(3:25, 27)])
ggcorr(data_corr[,c(13:25, 27)], label = TRUE)
```
Наиболее важны признаки состояния: V13, V14, V19, V22, V24

``` {r, echo = FALSE}
ggcorr(data_corr[,c(3:12, 13, 14, 19, 22, 24)])
```

``` {r echo =FALSE}
ggplot(data = train_data, aes(x = Среднегодовой.доход.тыс, y = Оценка.благополучия)) + 
  geom_point(aes(color = Ощущаемое.счастье))
```

``` {r echo = FALSE}
ggplot(data = train_data, aes(x = Чувство.технологического.прогресса, group = Ощущаемое.счастье, fill = Ощущаемое.счастье)) + geom_density(alpha = 0.5) + geom_rug()
```

Модель для "Оценка.благополучия"
``` {r, include = FALSE, warning = FALSE}
aim2 <- "Оценка.благополучия"
factors2 <- setdiff(names(train_data[,3:12]), aim2)
formula_text2 <-paste0(aim2, " ~ ", paste0(factors2, collapse = "+"))
MyFormula2 <- as.formula(formula_text2)
LM2_full <- lm(data = train_data, MyFormula2)
```

```{r echo=FALSE, include=FALSE}
LM2_optimal <- step(LM2_full, direction='backward') # алгоритм для поиска оптимальной модели 
summary(LM2_optimal)
```

```{r echo=FALSE}
formula2_optimal <- "Оценка.благополучия ~ Среднегодовой.доход.тыс + 
    Объем.потребленного.алкоголя.в.год.л. + 
    Охват.беспроводной.связи.в.сообществе + 
    Количество.смертей.от.вирусных.и.респираторных.заболеваний.в.сообществе.тыс..человек + 
    Волатильность.потребительских.цен.в.сообществе"
LM2 <- lm(formula2_optimal, data = train_data)
summary(LM2)
```

Модель дл Оценка.социальной.поддержки
``` {r, include = FALSE, warning = FALSE}
aim3 <- "Оценка.социальной.поддержки"
factors3 <- setdiff(names(train_data[,3:12]), aim3)
formula_text3 <-paste0(aim3, " ~ ", paste0(factors3, collapse = "+"))
MyFormula3 <- as.formula(formula_text3)
LM3_full <- lm(data = train_data, MyFormula3)
```

```{r echo=FALSE, include=FALSE}
LM3_optimal <- step(LM3_full, direction='backward') # алгоритм для поиска оптимальной модели 
summary(LM3_optimal)
```

```{r echo=FALSE}
formula3_optimal <- "Оценка.социальной.поддержки ~ Объем.потребленного.алкоголя.в.год.л. + 
    Количество.членов.семьи + Доля.от.дохода.семьи.которая.тратится.на.продовольствие + 
    Коэффициент.Джини.сообщества + 
    Количество.смертей.от.вирусных.и.респираторных.заболеваний.в.сообществе.тыс..человек"
LM3 <- lm(formula3_optimal, data = train_data)
summary(LM3)
```

``` {r, include = FALSE, warning = FALSE}
aim4 <- "Оценка.риска.безработицы" 
factors4 <- setdiff(names(train_data[,3:12]), aim4)
formula_text4 <-paste0(aim4, " ~ ", paste0(factors4, collapse = "+"))
MyFormula4 <- as.formula(formula_text4)
LM4_full <- lm(data = train_data, MyFormula4)
```

```{r echo=FALSE, include=FALSE}
LM4_optimal <- step(LM4_full, direction='backward') # алгоритм для поиска оптимальной модели 
summary(LM4_optimal)
```

```{r echo=FALSE}
formula4_optimal <- "Оценка.риска.безработицы ~ Среднегодовой.доход.тыс + 
    Коэффициент.Джини.сообщества + 
    Издержки.сообщества.на.окружающую.среду.млн. + 
    Охват.беспроводной.связи.в.сообществе"
LM4 <- lm(formula4_optimal, data = train_data)
summary(LM4)
```

``` {r, include = FALSE, warning = FALSE}
aim5 <- "Индекс.семьи" 
factors5 <- setdiff(names(train_data[,3:12]), aim5)
formula_text5 <-paste0(aim5, " ~ ", paste0(factors5, collapse = "+"))
MyFormula5 <- as.formula(formula_text5)
LM5_full <- lm(data = train_data, MyFormula5)
```

```{r echo=FALSE, include=FALSE}
LM5_optimal <- step(LM5_full, direction='backward') # алгоритм для поиска оптимальной модели 
summary(LM5_optimal)
```

```{r echo=FALSE}
formula5_optimal <- "Индекс.семьи ~ Среднегодовой.доход.тыс + 
    Доля.от.дохода.семьи.которая.тратится.на.продовольствие + 
    Издержки.сообщества.на.окружающую.среду.млн."
LM5 <- lm(formula5_optimal, data = train_data)
summary(LM5)
```

``` {r, include = FALSE, warning = FALSE}
aim6 <- "Чувство.технологического.прогресса"
factors6 <- setdiff(names(train_data[,3:12]), aim6)
formula_text6 <-paste0(aim6, " ~ ", paste0(factors6, collapse = "+"))
MyFormula6 <- as.formula(formula_text6)
LM6_full <- lm(data = train_data, MyFormula6)
```

```{r echo=FALSE, include=FALSE}
LM6_optimal <- step(LM6_full, direction='backward') # алгоритм для поиска оптимальной модели 
summary(LM6_optimal)
```

```{r echo=FALSE}
formula6_optimal <- "Чувство.технологического.прогресса ~ 
    Объем.потребленного.алкоголя.в.год.л. + 
        Количество.членов.семьи + Количество.лет.образования + 
        Коэффициент.Джини.сообщества + 
        Охват.беспроводной.связи.в.сообществе + 
        Количество.смертей.от.вирусных.и.респираторных.заболеваний.в.сообществе.тыс..человек"
LM6 <- lm(formula6_optimal, data = train_data)
summary(LM6)
```

``` {r, include =FALSE}
rang <- c(1:10)
td2 <- train_data
td2$Ощущаемое.счастье <- as.character(td2$Ощущаемое.счастье)
td2$Ощущаемое.счастье_Шкала <- td2$Ощущаемое.счастье
for (i in 1:10) {
  td2[td2$Ощущаемое.счастье == the_cantril_scale[i], 27] <- as.numeric(rang[i])
}
```

``` {r, include = FALSE, warning = FALSE}
MyFormula1 <- "Ощущаемое.счастье_Шкала ~ 
  Оценка.благополучия +
  Оценка.социальной.поддержки +
  Оценка.риска.безработицы +
  Индекс.семьи +
  Чувство.технологического.прогресса +
  
  I(Оценка.благополучия**(1/2)) +
  I(Оценка.социальной.поддержки**(1/2)) +
  I(Оценка.риска.безработицы**(1/2)) +
  I(Индекс.семьи**(1/2)) +
  I(Чувство.технологического.прогресса**(1/2)) +
  
  I(Оценка.благополучия**(1/3)) +
  I(Оценка.социальной.поддержки**(1/3)) +
  I(Оценка.риска.безработицы**(1/3)) +
  I(Индекс.семьи**(1/3)) +
  I(Чувство.технологического.прогресса**(1/3)) +
  
  I(Оценка.благополучия**(1/4)) +
  I(Оценка.социальной.поддержки**(1/4)) +
  I(Оценка.риска.безработицы**(1/4)) +
  I(Индекс.семьи**(1/4)) +
  I(Чувство.технологического.прогресса**(1/4)) +
  
  I(Оценка.благополучия**(1/5)) +
  I(Оценка.социальной.поддержки**(1/5)) +
  I(Оценка.риска.безработицы**(1/5)) +
  I(Индекс.семьи**(1/5)) +
  I(Чувство.технологического.прогресса**(1/5)) +
  
  I(Оценка.благополучия**2) +
  I(Оценка.социальной.поддержки**2) +
  I(Оценка.риска.безработицы**2) +
  I(Индекс.семьи**2) +
  I(Чувство.технологического.прогресса**2) +  
  
  I(Оценка.благополучия**3) +
  I(Оценка.социальной.поддержки**3) +
  I(Оценка.риска.безработицы**3)+
  I(Индекс.семьи**3)+
  I(Чувство.технологического.прогресса**3) +
  
  I(Оценка.благополучия**4) +
  I(Оценка.социальной.поддержки**4) +
  I(Оценка.риска.безработицы**4) +
  I(Индекс.семьи**4) +
  I(Чувство.технологического.прогресса**4) +  
  
  I(Оценка.благополучия**5) +
  I(Оценка.социальной.поддержки**5) +
  I(Оценка.риска.безработицы**5) +
  I(Индекс.семьи**5) +
  I(Чувство.технологического.прогресса**5) +  
  
  I(Оценка.благополучия**6) +
  I(Оценка.социальной.поддержки**6) +
  I(Оценка.риска.безработицы**6) +
  I(Индекс.семьи**6) +
  I(Чувство.технологического.прогресса**6) +  
  
  I(Оценка.благополучия**7) +
  I(Оценка.социальной.поддержки**7) +
  I(Оценка.риска.безработицы**7) +
  I(Индекс.семьи**7) +
  I(Чувство.технологического.прогресса**7) +  
  
  I(Оценка.благополучия**8) +
  I(Оценка.социальной.поддержки**8) +
  I(Оценка.риска.безработицы**8) +
  I(Индекс.семьи**8) +
  I(Чувство.технологического.прогресса**8) +  
  
  I(Оценка.благополучия**9) +
  I(Оценка.социальной.поддержки**9) +
  I(Оценка.риска.безработицы**9) +
  I(Индекс.семьи**9) +
  I(Чувство.технологического.прогресса**9) +  

  I(Оценка.благополучия**10) +
  I(Оценка.социальной.поддержки**10) +
  I(Оценка.риска.безработицы**10) +
  I(Индекс.семьи**10) +
  I(Чувство.технологического.прогресса**10) +  
  
  I(Оценка.благополучия**11) +
  I(Оценка.социальной.поддержки**11) +
  I(Оценка.риска.безработицы**11) +
  I(Индекс.семьи**11) +
  I(Чувство.технологического.прогресса**11) +  
  
  I(Оценка.благополучия**12) +
  I(Оценка.социальной.поддержки**12) +
  I(Оценка.риска.безработицы**12) +
  I(Индекс.семьи**12) +
  I(Чувство.технологического.прогресса**12) +  
  
  I(Оценка.благополучия**13) +
  I(Оценка.социальной.поддержки**13) +
  I(Оценка.риска.безработицы**13) +
  I(Индекс.семьи**13) +
  I(Чувство.технологического.прогресса**13) +  
  
  I(Оценка.благополучия**14) +
  I(Оценка.социальной.поддержки**14) +
  I(Оценка.риска.безработицы**14) +
  I(Индекс.семьи**14) +
  I(Чувство.технологического.прогресса**14) +  
  
  I(Оценка.благополучия**15) +
  I(Оценка.социальной.поддержки**15) +
  I(Оценка.риска.безработицы**15) +
  I(Индекс.семьи**15) +
  I(Чувство.технологического.прогресса**15) +  
  
  I(Оценка.благополучия**16) +
  I(Оценка.социальной.поддержки**16) +
  I(Оценка.риска.безработицы**16) +
  I(Индекс.семьи**16) +
  I(Чувство.технологического.прогресса**16) +  
  
  I(Оценка.благополучия**17) +
  I(Оценка.социальной.поддержки**17) +
  I(Оценка.риска.безработицы**17) +
  I(Индекс.семьи**17) +
  I(Чувство.технологического.прогресса**17) +
  
  I(log(Оценка.благополучия)) +
  I(log(Оценка.социальной.поддержки)) +
  I(log(Оценка.риска.безработицы)) +
  I(log(Индекс.семьи)) +
  I(log(Чувство.технологического.прогресса)) +  
  
  I(exp(Оценка.благополучия)) +
  I(exp(Оценка.социальной.поддержки)) +
  I(exp(Оценка.риска.безработицы)) +
  I(exp(Индекс.семьи)) +
  I(exp(Чувство.технологического.прогресса)) +  
  
  I(Оценка.благополучия*Оценка.социальной.поддержки*Оценка.риска.безработицы*Индекс.семьи*Чувство.технологического.прогресса) +
  I(Оценка.благополучия*Оценка.социальной.поддержки) +
  I(Оценка.благополучия*Оценка.риска.безработицы) +
  I(Оценка.благополучия*Индекс.семьи) +
  I(Оценка.благополучия*Чувство.технологического.прогресса) +
  I(Оценка.социальной.поддержки*Оценка.риска.безработицы) +
  I(Оценка.социальной.поддержки*Индекс.семьи) +
  I(Оценка.социальной.поддержки*Чувство.технологического.прогресса) +
  I(Оценка.риска.безработицы*Индекс.семьи) +
  I(Оценка.риска.безработицы*Чувство.технологического.прогресса) +
  I(Индекс.семьи*Чувство.технологического.прогресса) +
  
  I((Оценка.благополучия*Оценка.социальной.поддержки*Оценка.риска.безработицы*Индекс.семьи*Чувство.технологического.прогресса)**2) +
  I((Оценка.благополучия*Оценка.социальной.поддержки)**2) +
  I((Оценка.благополучия*Оценка.риска.безработицы)**2) +
  I((Оценка.благополучия*Индекс.семьи)**2) +
  I((Оценка.благополучия*Чувство.технологического.прогресса)**2) +
  I((Оценка.социальной.поддержки*Оценка.риска.безработицы)**2) +
  I((Оценка.социальной.поддержки*Индекс.семьи)**2) +
  I((Оценка.социальной.поддержки*Чувство.технологического.прогресса)**2) +
  I((Оценка.риска.безработицы*Индекс.семьи)**2) +
  I((Оценка.риска.безработицы*Чувство.технологического.прогресса)**2) +
  I((Индекс.семьи*Чувство.технологического.прогресса)**2) +
  
  I((Оценка.благополучия*Оценка.социальной.поддержки*Оценка.риска.безработицы*Индекс.семьи*Чувство.технологического.прогресса)**3) +
  I((Оценка.благополучия*Оценка.социальной.поддержки)**3) +
  I((Оценка.благополучия*Оценка.риска.безработицы)**3) +
  I((Оценка.благополучия*Индекс.семьи)**3) +
  I((Оценка.благополучия*Чувство.технологического.прогресса)**3) +
  I((Оценка.социальной.поддержки*Оценка.риска.безработицы)**3) +
  I((Оценка.социальной.поддержки*Индекс.семьи)**3) +
  I((Оценка.социальной.поддержки*Чувство.технологического.прогресса)**3) +
  I((Оценка.риска.безработицы*Индекс.семьи)**3) +
  I((Оценка.риска.безработицы*Чувство.технологического.прогресса)**3) +
  I((Индекс.семьи*Чувство.технологического.прогресса)**3) +
  
  I((Оценка.благополучия*Оценка.социальной.поддержки*Оценка.риска.безработицы*Индекс.семьи*Чувство.технологического.прогресса)**4) +
  I((Оценка.благополучия*Оценка.социальной.поддержки)**4) +
  I((Оценка.благополучия*Оценка.риска.безработицы)**4) +
  I((Оценка.благополучия*Индекс.семьи)**4) +
  I((Оценка.благополучия*Чувство.технологического.прогресса)**4) +
  I((Оценка.социальной.поддержки*Оценка.риска.безработицы)**4) +
  I((Оценка.социальной.поддержки*Индекс.семьи)**4) +
  I((Оценка.социальной.поддержки*Чувство.технологического.прогресса)**4) +
  I((Оценка.риска.безработицы*Индекс.семьи)**4) +
  I((Оценка.риска.безработицы*Чувство.технологического.прогресса)**4) +
  I((Индекс.семьи*Чувство.технологического.прогресса)**4) +
  
  I((Оценка.благополучия*Оценка.социальной.поддержки*Оценка.риска.безработицы*Индекс.семьи*Чувство.технологического.прогресса)**5) +
  I((Оценка.благополучия*Оценка.социальной.поддержки)**5) +
  I((Оценка.благополучия*Оценка.риска.безработицы)**5) +
  I((Оценка.благополучия*Индекс.семьи)**5) +
  I((Оценка.благополучия*Чувство.технологического.прогресса)**5) +
  I((Оценка.социальной.поддержки*Оценка.риска.безработицы)**5) +
  I((Оценка.социальной.поддержки*Индекс.семьи)**5) +
  I((Оценка.социальной.поддержки*Чувство.технологического.прогресса)**5) +
  I((Оценка.риска.безработицы*Индекс.семьи)**5) +
  I((Оценка.риска.безработицы*Чувство.технологического.прогресса)**5) +
  I((Индекс.семьи*Чувство.технологического.прогресса)**5)
"
LM1 <- lm(data = td2, MyFormula1)
```

``` {r, include = FALSE, warning = FALSE}
test_data2 <- test_data[, 3:12]
pred1 <- predict(LM2, test_data2)
pred2 <- predict(LM3, test_data2)
pred3 <- predict(LM4, test_data2)
pred4 <- predict(LM5, test_data2)
pred5 <- predict(LM6, test_data2)

test_data2$Оценка.благополучия <- pred1
test_data2$Оценка.социальной.поддержки <- pred2
test_data2$Оценка.риска.безработицы <- pred3
test_data2$Индекс.семьи <- pred4
test_data2$Чувство.технологического.прогресса <- pred5

main_pred <- predict(LM1, test_data2)
test_data2$result <- round(main_pred)

```

``` {r, include = FALSE, warning = FALSE}
test_data2$Ощущаемое.счастье <- test_data$Ощущаемое.счастье
test_data2$Ощущаемое.счастье_Прогноз <- test_data2$result
for (i in 1:10){
  test_data2[test_data2$Ощущаемое.счастье_Прогноз == i, 18] <- the_cantril_scale[i]
}
```

``` {r , include = FALSE, warning = FALSE}
ccc <- 0
for (i in 1:nrow(test_data2)){
  if (test_data2[i,18] == test_data2[i,17]){
    ccc <- ccc + 1
  }
}
res <- ccc/nrow(test_data2)
```

### Точность модели 69%

```{r echo=FALSE, include=FALSE}
no_data$Оценка.благополучия <- predict(LM1, no_data)
no_data$Оценка.социальной.поддержки <- predict(LM2, no_data)
no_data$Индекс.Щедрости <- predict(LM3, no_data)
no_data$Индекс.отношения.к.коррупции <- predict(LM4, no_data)
no_data$Индекс.страха.социальных.конфликтов <- predict(LM5, no_data)

no_data$Ощущаемое.счастье <- round(predict(LM_main, no_data))
for (i in 1:10){
  no_data[no_data$Ощущаемое.счастье == i, 26] <- the_cantril_scale[i]
}

```










